name: pandera-dev
channels:
  - conda-forge

dependencies:
  # environment management
  - pip

  # pandera dependencies
  - packaging >= 20.0
  - hypothesis >= 5.41.1
  - numpy >= 1.9.0
  - pandas
  - scipy
  - wrapt
  - pyyaml >=5.1
  - typing_inspect >= 0.6.0
  - typing_extensions >= 3.7.4.3
  - frictionless
  - pyarrow

  # testing and dependencies
  - black >= 20.8b1

  # testing
  - isort >= 5.7.0
  - codecov
  - mypy >= 0.902 # mypy no longer bundle stubs for third-party libraries
  - pylint >= 2.7.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - xdoctest
  - setuptools >= 52.0.0
  - nox = 2020.12.31 # pinning due to UnicodeDecodeError, see https://github.com/pandera-dev/pandera/pull/504/checks?check_run_id=2841360122
  - importlib_metadata # required if python < 3.8

  # documentation
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - recommonmark

  # packaging
  - twine

  # performance testing
  - asv

  # optional
  - pre_commit

  - pip:
    - furo==2021.6.18b36
    - types-click
    - types-pyyaml
    - types-pkg_resources
