name: pandera-dev
channels:
  - conda-forge

dependencies:
  # environment management
  - pip

  # pandera dependencies
  - packaging >= 20.0
  - hypothesis >= 5.41.1
  - numpy >= 1.9.0
  - pandas
  - scipy
  - wrapt
  - pyyaml >=5.1
  - typing_inspect >= 0.6.0
  - typing_extensions >= 3.7.4.3

  # testing and dependencies
  - black >= 20.8b1

  # testing
  - isort >= 5.7.0
  - codecov
  - mypy = 0.812  # TODO: update codebase to be 0.902+ compatible
  - pylint >= 2.7.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-asyncio
  - setuptools >= 52.0.0
  - nox = 2020.12.31  # TODO: update codebase to be 2021.6.6+ compatible
  - importlib_metadata # required if python < 3.8

  # documentation
  - sphinx = 3.5.4  # pinned due to doc-building error https://github.com/pandera-dev/pandera/runs/2601459267
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - recommonmark

  # packaging
  - twine

  # performance testing
  - asv

  # optional
  - pre_commit

  - pip:
    - furo==2021.6.18b36
