name: pandera-dev
channels:
  - conda-forge

dependencies:
  # environment management
  - pip

  # pandera dependencies
  - packaging >= 20.0
  - hypothesis >= 5.41.1
  - numpy >= 1.19.0
  - pandas >= 1.2.0
  - scipy
  - wrapt
  - pyyaml >=5.1
  - typing_inspect >= 0.6.0
  - typing_extensions >= 3.7.4.3
  - frictionless <= 4.40.8  # v5.* introduces breaking changes
  - pyarrow
  - pydantic
  - multimethod
  - typeguard

  # mypy extra
  - pandas-stubs <= 1.5.2.221213

  # pyspark extra
  - pyspark >= 3.2.0

  # modin extra
  - modin
  - protobuf <= 3.20.3

  # dask extra
  - dask
  - distributed

  # geopandas extra
  - geopandas
  - shapely

  # fastapi extra
  - fastapi

  # testing and dependencies
  - black >= 22.1.0

  # testing
  - isort >= 5.7.0
  - mypy <= 0.982
  - pylint <= 2.17.3
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-asyncio
  - pytz
  - xdoctest
  - nox
  - importlib_metadata # required if python < 3.8

  # fastapi testing
  - uvicorn
  - python-multipart

  # documentation
  - sphinx
  - sphinx-panels
  - sphinx-autodoc-typehints <= 1.14.1
  - sphinx-copybutton
  - recommonmark

  # packaging
  - twine

  # performance testing
  - asv >= 0.5.1

  # optional
  - pre_commit

  - pip:
      - furo
      - ray
      - types-click
      - types-pyyaml
      - types-pkg_resources
      - types-requests
      - types-pytz
      - jupyterlite
      - jupyterlite_sphinx
