name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - wrapt
  - pip:
    - pandera >= 0.19.0
    - pydantic >= 2.0.0
    - multimethod
    - packaging
    - typeguard
    - typing_inspect
    - mypy_extensions
