name: CI Tests
on:
  push:
    branches:
    - master
    - dev
    - bugfix
    - 'release/*'
  pull_request:
    branches:
    - master
    - dev
    - bugfix
    - 'release/*'

env:
  DEFAULT_PYTHON: 3.8
  CI: "true"
  # Increase this value to reset cache if environment.yml has not changed
  CACHE_VERSION: 4

jobs:
  codestyle:
    name: Code Style
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: |
            ~/conda_pkgs_dir
            .nox
          key: "${{ runner.os }}\
            -codestyle-${{ env.CACHE_VERSION }}\
            -${{ env.DEFAULT_PYTHON }}\
            -${{ hashFiles('environment.yml') }}"

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          activate-environment: pandera-dev
          auto-update-conda: false
          environment-file: environment.yml
          use-only-tar-bz2: true
          auto-activate-base: false

      - name: Conda info
        run: |
          conda info
          conda list

      - name: Check isort and black formatting
        run: >
          nox
          -db conda -r
          --non-interactive
          --session black isort

  lint:
    name: Linters (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: |
            ~/conda_pkgs_dir
            .nox
          key: "${{ runner.os }}\
            -lint-${{ env.CACHE_VERSION }}\
            -${{ matrix.python-version }}\
            -${{ hashFiles('environment.yml') }}"

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          activate-environment: pandera-dev
          auto-update-conda: false
          environment-file: environment.yml
          use-only-tar-bz2: true
          auto-activate-base: false

      - name: Conda info
        run: |
          conda info
          conda list

      - name: Check requirements
        run: >
          nox
          -db conda -r
          --non-interactive
          --python ${{ matrix.python-version }}
          --session requirements-${{ matrix.python-version }}

      - name: Pylint
        run: >
          nox
          -db conda -r
          --non-interactive
          --python ${{ matrix.python-version }}
          --session lint-${{ matrix.python-version }}

      - name: Mypy Type Checking
        run: >
          nox
          -db conda -r
          --non-interactive
          --python ${{ matrix.python-version }}
          --session mypy-${{ matrix.python-version }}

  tests:
    name: >
      CI Tests (${{ matrix.python-version }},
      ${{ matrix.os }},
      pandas-${{ matrix.pandas-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        pandas-version: ["latest", "0.25.3"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: |
            ~/conda_pkgs_dir
            .nox
          key: "${{ runner.os }}\
            -tests-${{ env.CACHE_VERSION }}\
            -${{ matrix.python-version }}\
            -${{ hashFiles('environment.yml') }}"

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          activate-environment: pandera-dev
          auto-update-conda: false
          environment-file: environment.yml
          use-only-tar-bz2: true
          auto-activate-base: false

      - name: Conda info
        run: |
          conda info
          conda list

      - name: Unit Tests - Core
        run: >
          nox
          -db conda -r -v
          --non-interactive
          --session "tests-${{ matrix.python-version }}(extra='core', pandas='${{ matrix.pandas-version }}')"

      - name: Unit Tests - Hypotheses
        run: >
          nox
          -db conda -r -v
          --non-interactive
          --session "tests-${{ matrix.python-version }}(extra='hypotheses', pandas='${{ matrix.pandas-version }}')"

      - name: Unit Tests - IO
        run: >
          nox
          -db conda -r -v
          --non-interactive
          --session "tests-${{ matrix.python-version }}(extra='io', pandas='${{ matrix.pandas-version }}')"

      - name: Unit Tests - Strategies
        run: >
          nox
          -db conda -r -v
          --non-interactive
          --session "tests-${{ matrix.python-version }}(extra='strategies', pandas='${{ matrix.pandas-version }}')"

      - name: Upload coverage to Codecov
        uses: "codecov/codecov-action@v1"

      - name: Check Docs
        run: >
          nox
          -db conda -r -v
          --non-interactive
          --session "docs-${{ matrix.python-version }}(pandas='${{ matrix.pandas-version }}')"
